# Generated by Django 6.0.4 on 2026-04-16 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bisync', '0002_bisynctarget'),
    ]

    operations = [
        migrations.AddField(
            model_name='bisynctask',
            name='debounce_seconds',
            field=models.FloatField(default=1.0, help_text='检测到变更后延迟多少秒再同步（默认 1.0）', verbose_name='防抖延迟(秒)'),
        ),
        migrations.AddField(
            model_name='bisynctask',
            name='exclude_patterns',
            field=models.TextField(blank=True, default='', help_text='每行一个 glob 模式，如 __pycache__  *.pyc  node_modules', verbose_name='排除模式'),
        ),
    ]
