# Generated by Django 6.0.4 on 2026-04-16 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BisyncTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='任务名称')),
                ('source_dir', models.CharField(max_length=500, verbose_name='源目录')),
                ('target_dir', models.CharField(max_length=500, verbose_name='目标目录')),
                ('interval', models.IntegerField(default=3, verbose_name='轮询间隔(秒)')),
                ('status', models.CharField(choices=[('stopped', '已停止'), ('running', '运行中'), ('error', '错误')], default='stopped', max_length=20, verbose_name='状态')),
                ('pid', models.IntegerField(blank=True, null=True, verbose_name='进程ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'Bisync 任务',
                'ordering': ['-created_at'],
            },
        ),
    ]
