# Generated by Django 6.0.4 on 2026-04-16 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sync2PodTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='任务名称')),
                ('source_dir', models.CharField(max_length=500, verbose_name='本地源目录')),
                ('namespace', models.CharField(default='default', max_length=100, verbose_name='命名空间')),
                ('pod', models.CharField(max_length=200, verbose_name='Pod 名称')),
                ('container', models.CharField(blank=True, max_length=100, verbose_name='容器名称')),
                ('pod_dir', models.CharField(max_length=500, verbose_name='Pod 内目标路径')),
                ('interval', models.IntegerField(default=3, verbose_name='轮询间隔(秒)')),
                ('status', models.CharField(choices=[('stopped', '已停止'), ('running', '运行中'), ('error', '错误')], default='stopped', max_length=20, verbose_name='状态')),
                ('pid', models.IntegerField(blank=True, null=True, verbose_name='进程ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'Sync2Pod 任务',
                'ordering': ['-created_at'],
            },
        ),
    ]
