# Generated by Django 6.0.4 on 2026-04-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync2pod', '0006_add_sync2podconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='sync2podconfig',
            name='show_list_log',
            field=models.BooleanField(default=True, help_text='启用后，任务列表操作栏显示日志按钮，可展开内联日志面板', verbose_name='列表页显示日志'),
        ),
    ]
