# Generated by Django 3.2.7 on 2026-06-11 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JiraIssue',
            fields=[
                ('issue_key', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('project_key', models.CharField(db_index=True, max_length=32)),
                ('summary', models.TextField()),
                ('status', models.CharField(db_index=True, max_length=64)),
                ('assignee', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('reporter', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('priority', models.CharField(blank=True, max_length=64, null=True)),
                ('sprint', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('raw_json', models.TextField()),
                ('last_seen_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='JiraSyncProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('profile_type', models.CharField(choices=[('my_issues', 'My Issues'), ('project', 'Project'), ('custom_jql', 'Custom JQL')], max_length=32)),
                ('params_json', models.JSONField(blank=True, default=dict)),
                ('jql', models.TextField()),
                ('is_default', models.BooleanField(default=False)),
                ('last_cursor', models.CharField(blank=True, max_length=128, null=True)),
                ('last_full_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_incremental_sync_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(is_default=True), fields=('is_default',), name='jira_workspace_single_default_profile')],
            },
        ),
        migrations.CreateModel(
            name='JiraSyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_type', models.CharField(choices=[('full', 'Full'), ('incremental', 'Incremental')], max_length=32)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='queued', max_length=32)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('fetched_count', models.IntegerField(default=0)),
                ('inserted_count', models.IntegerField(default=0)),
                ('updated_count', models.IntegerField(default=0)),
                ('skipped_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_runs', to='jira_workspace.jirasyncprofile')),
            ],
        ),
        migrations.CreateModel(
            name='JiraSavedQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('filters_json', models.JSONField(blank=True, default=dict)),
                ('jql_text', models.TextField(blank=True)),
                ('is_starred', models.BooleanField(default=False)),
                ('is_pinned', models.BooleanField(default=False)),
                ('sort_by', models.CharField(default='updated_at', max_length=32)),
                ('sort_order', models.CharField(default='desc', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_queries', to='jira_workspace.jirasyncprofile')),
            ],
        ),
        migrations.CreateModel(
            name='JiraIssueMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_time_minutes', models.IntegerField(blank=True, null=True)),
                ('worklog_minutes', models.IntegerField(blank=True, null=True)),
                ('status_changed_at', models.DateTimeField(blank=True, null=True)),
                ('issue', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='jira_workspace.jiraissue')),
            ],
        ),
    ]
