# Generated by Django 3.2.7 on 2026-06-11 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jira_workspace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JiraIssueSyncMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_seen_at', models.DateTimeField()),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_memberships', to='jira_workspace.jiraissue')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_memberships', to='jira_workspace.jirasyncprofile')),
            ],
        ),
        migrations.AddConstraint(
            model_name='jiraissuesyncmembership',
            constraint=models.UniqueConstraint(fields=('issue', 'profile'), name='jira_workspace_unique_issue_profile_membership'),
        ),
    ]
