# Generated by Codex on 2026-06-13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jira_workspace", "0003_workspace_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkspaceStar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("route", "Route"),
                            ("saved_query", "Saved Query"),
                            ("jira_sync_profile", "Jira Sync Profile"),
                            ("sync2pod_profile", "sync2pod Profile"),
                        ],
                        max_length=48,
                    ),
                ),
                ("label", models.CharField(max_length=160)),
                ("route", models.CharField(max_length=255)),
                ("group_key", models.CharField(db_index=True, max_length=80)),
                ("object_id", models.CharField(blank=True, default="", max_length=80)),
                ("position", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["position", "created_at", "label"],
            },
        ),
        migrations.AddConstraint(
            model_name="workspacestar",
            constraint=models.UniqueConstraint(
                fields=("kind", "route", "object_id"),
                name="jira_workspace_unique_workspace_star",
            ),
        ),
    ]
