# Generated by Django 3.2.7 on 2026-06-14 13:25

from django.db import migrations, models
import jira_workspace.models


class Migration(migrations.Migration):

    dependencies = [
        ('jira_workspace', '0004_workspace_star'),
    ]

    operations = [
        migrations.AddField(
            model_name='jirasavedquery',
            name='card_kind',
            field=models.CharField(choices=[('jira_issue_query', 'Jira Issue Query')], default='jira_issue_query', max_length=48),
        ),
        migrations.AddField(
            model_name='jirasavedquery',
            name='default_columns_json',
            field=models.JSONField(blank=True, default=jira_workspace.models.default_query_card_columns),
        ),
        migrations.AddField(
            model_name='jirasavedquery',
            name='default_page_size',
            field=models.PositiveIntegerField(default=25),
        ),
        migrations.AddField(
            model_name='jirasavedquery',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='jirasavedquery',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jirasavedquery',
            name='query_syntax',
            field=models.CharField(choices=[('local_filter', 'Local Filter'), ('jql_text', 'JQL Text'), ('saved_filter_reference', 'Saved Filter Reference')], default='local_filter', max_length=48),
        ),
        migrations.AddField(
            model_name='jirasavedquery',
            name='summary_metrics_json',
            field=models.JSONField(blank=True, default=jira_workspace.models.default_query_card_summary_metrics),
        ),
    ]
