# Generated by Codex on 2026-06-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jira_workspace", "0005_jirasavedquery_query_card_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jirasavedquery",
            name="card_kind",
            field=models.CharField(default="jira_issue_query", max_length=48),
        ),
    ]
