# Generated by Codex on 2026-06-15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jira_workspace", "0006_open_query_card_kind_choices"),
    ]

    operations = []
