# Generated by Django 3.2.7 on 2026-06-14 16:04

import json

from django.db import migrations, models


def backfill_issue_metadata(apps, schema_editor):
    JiraIssue = apps.get_model('jira_workspace', 'JiraIssue')
    for issue in JiraIssue.objects.all().iterator():
        try:
            raw = json.loads(issue.raw_json or '{}')
        except (TypeError, ValueError):
            raw = {}
        fields = raw.get('fields') or {}
        issue_type = fields.get('issuetype') or {}
        labels = fields.get('labels') or []
        if isinstance(issue_type, dict):
            issue_type = issue_type.get('name') or issue_type.get('displayName') or issue_type.get('value') or ''
        if not isinstance(labels, list):
            labels = [labels] if labels else []
        issue.issue_type = str(issue_type or '')
        issue.labels_json = [str(label).strip() for label in labels if str(label).strip()]
        issue.save(update_fields=['issue_type', 'labels_json'])


class Migration(migrations.Migration):

    dependencies = [
        ('jira_workspace', '0007_open_query_card_kind_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='jiraissue',
            name='issue_type',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='jiraissue',
            name='labels_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RunPython(backfill_issue_metadata, migrations.RunPython.noop),
    ]
