# Generated by Django 6.0.4 on 2026-04-16 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync2pod', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sync2podtask',
            name='cluster',
            field=models.CharField(blank=True, max_length=200, verbose_name='集群名称'),
        ),
    ]
