# Generated by Django 6.0.4 on 2026-04-16 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync2pod', '0002_sync2podtask_cluster'),
    ]

    operations = [
        migrations.AddField(
            model_name='sync2podtask',
            name='pod_label',
            field=models.CharField(blank=True, help_text='优先级高于 Pod 名称，e.g. app=myapp,env=dev', max_length=500, verbose_name='Pod 标签选择器'),
        ),
        migrations.AddField(
            model_name='sync2podtask',
            name='pod_type',
            field=models.CharField(choices=[('k8s', 'Kubernetes Pod'), ('docker', 'Docker 容器')], default='k8s', max_length=20, verbose_name='Pod 类型'),
        ),
        migrations.AlterField(
            model_name='sync2podtask',
            name='pod',
            field=models.CharField(blank=True, help_text='pod_label 为空时使用', max_length=200, verbose_name='Pod 名称'),
        ),
        migrations.AlterField(
            model_name='sync2podtask',
            name='pod_dir',
            field=models.CharField(max_length=500, verbose_name='Pod 内目标路径'),
        ),
    ]
