# Generated by Django 6.0.4 on 2026-04-16 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync2pod', '0004_sync2podtask_is_tess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sync2podtask',
            name='is_tess',
            field=models.BooleanField(default=True, help_text='启用后 kubectl 替换为 tess kubectl', verbose_name='Tess 环境'),
        ),
    ]
