# Generated by Django 6.0.4 on 2026-04-16 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync2pod', '0005_is_tess_default_true'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sync2PodConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_tess', models.BooleanField(default=True, help_text='启用后，新建任务默认勾选 tess kubectl；已有任务不受影响', verbose_name='Tess 环境（全局默认）')),
            ],
            options={
                'verbose_name': 'Sync2Pod 全局配置',
            },
        ),
    ]
