# Generated by Django 6.0.4 on 2026-04-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync2pod', '0007_add_show_list_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='sync2podconfig',
            name='alert_email',
            field=models.CharField(blank=True, help_text='为空则不发送告警邮件', max_length=200, verbose_name='告警收件邮箱'),
        ),
        migrations.AddField(
            model_name='sync2podconfig',
            name='smtp_host',
            field=models.CharField(blank=True, help_text='e.g. smtp.gmail.com', max_length=200, verbose_name='SMTP 主机'),
        ),
        migrations.AddField(
            model_name='sync2podconfig',
            name='smtp_password',
            field=models.CharField(blank=True, max_length=500, verbose_name='SMTP 密码'),
        ),
        migrations.AddField(
            model_name='sync2podconfig',
            name='smtp_port',
            field=models.IntegerField(default=587, verbose_name='SMTP 端口'),
        ),
        migrations.AddField(
            model_name='sync2podconfig',
            name='smtp_use_tls',
            field=models.BooleanField(default=True, verbose_name='使用 TLS'),
        ),
        migrations.AddField(
            model_name='sync2podconfig',
            name='smtp_user',
            field=models.CharField(blank=True, max_length=200, verbose_name='SMTP 用户名'),
        ),
        migrations.AddField(
            model_name='sync2podtask',
            name='enable_alert',
            field=models.BooleanField(default=True, help_text='非主动停止时发送邮件告警（需配置全局 SMTP）', verbose_name='异常停止告警'),
        ),
    ]
